<?php

namespace protocol\websocket;

use Exception;
use PHPUnit\Framework\TestCase;
use Surreal\Cbor\Types\RecordId;
use Surreal\Core\Client\SurrealWebsocket;

class BasicTest extends TestCase
{
    static private SurrealWebsocket $db;

    /**
     * @throws Exception
     */
    public static function setUpBeforeClass(): void
    {
        self::$db = new SurrealWebsocket(
            host: "ws://localhost:8000/rpc",
            target: ["namespace" => "test", "database" => "test"]
        );

        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws Exception
     */
    public function testUse(): void
    {
        $result = self::$db->use(["namespace" => "test", "database" => "test"]);
        $this->assertNull($result);
    }

    /**
     * @throws Exception
     */
    public function testLet(): void
    {
        $result = self::$db->let("x", 1);
        $this->assertNull($result);
    }

    /**
     * @throws Exception
     */
    public function testUnset(): void
    {
        $result = self::$db->unset("x");
        $this->assertNull($result);
    }

//    public function testInfo(): void
//    {
//        $token = self::$db->signin([
//            "email" => "beau@user.nl",
//            "pass" => "123!",
//            "NS" => "test",
//            "DB" => "test",
//            "SC" => "account"
//        ]);
//
//        $this->assertIsString($token);
//
//        $info = self::$db->info();
//
//        $this->assertIsArray($info);
//
//        $this->assertArrayHasKey("email", $info);
//        $this->assertArrayHasKey("id", $info);
//        $this->assertArrayHasKey("pass", $info);
//
//        $this->assertInstanceOf(RecordId::class, $info["id"]);
//    }

    public static function tearDownAfterClass(): void
    {
        self::$db->close();
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}