name: CI

permissions:
  contents: read
  pull-requests: read

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  phpstan:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Run static analysis
      run: composer analyse

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [v2.6.2]
        php_version: ['8.4']

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

      # setup php version
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist

    - name: SurrealDB in Github Actions
      uses: surrealdb/setup-surreal@v2
      with:
        surrealdb_version: ${{ matrix.version }}
        surrealdb_auth: true
        surrealdb_username: 'root'
        surrealdb_password: 'root'
        surrealdb_additional_args: --allow-all
        surrealdb_strict: true

    - name: Run tests
      env:
        SURREALDB_REQUIRE_LOCAL: '1'
      run: composer test
